config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    get :publish
    collection do
      get :my_posts
    end
  end

  resource :comments, only: [] do
    collection do
      scope '/:post_id' do
        post :add_comment
        patch :update_comment
      end
    end
  end

  resources :likes, only: [] do
    collection do
      get :toggle_likes
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "home#root"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < Post
  include Discard::Model
  self.discard_column = :deleted_at
  self.default_scopes = []
  default_scope -> { kept }
  acts_as_favoritable

  belongs_to :post, foreign_key: :parent_id
  belongs_to :user
  # has_many :favorites, as: :favoritable

  validates_presence_of :parent_id
  before_save :confirm

  def confirm
    self.status = 'published'
  end

end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  extend ActsAsFavoritor::FavoriteScopes

  belongs_to :favoritable, polymorphic: true
  belongs_to :favoritor, polymorphic: true

  def block!
    update!(blocked: true)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  include Discard::Model
  self.discard_column = :deleted_at
  default_scope -> { where(deleted_at: nil, type: nil) }
  acts_as_favoritable

  has_one_attached :media
  belongs_to :user
  has_many :comments, foreign_key: :parent_id, dependent: :destroy
  # has_many :favorites, as: :favoritable

  scope :published, -> { where(status: :published) }
  scope :drafted, -> { where(status: :draft) }

  enum status: {
    draft: 'draft',
    published: 'published'
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  acts_as_favoritor
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
  # has_many :favorites, as: :favoritor, dependant: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: %i[ add_comment ]

  def add_comment
    comment = @post.comments.build(params[:comment].to_enum.to_h)
    comment.user = current_user
    comment.save!
    respond_to do |format|
      format.html { redirect_to request.referer, notice: 'Commented!' }
      format.js { render inline: "location.reload();", notice: 'Commented!' }
    end
  end

  def update_comment
    comment = Comment.find(comment_params[:id])
    comment.update(comment_params)
    respond_to do |format|
      format.html { redirect_to request.referer, notice: 'Comment updated!' }
      format.js# { render notice: 'Comment updated!' }
    end
  end



  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:id, :body, :media, :user_id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def root
    redirect_to posts_path
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def toggle_likes
    obj_class = Kernel.const_get(params[:obj_type])
    obj = obj_class.find(params[:obj_id])
    if params[:obj_type] == 'Post'
      unless current_user.favorited?(obj)
        current_user.favorite(obj)
      else
        current_user.unfavorite(obj)
      end
    else
      unless params[:like] == 'true'
        fav = Favorite.create(favoritable: obj, favoritor: current_user)
      else
        fav = Favorite.where(favoritable: obj, favoritor: current_user).first
        fav.delete
      end
    end
    render json: {result: 'success', likes_count: obj.reload.favoritors.count }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy publish ]

  def index
    @posts = Post.published.page(params[:page]).per(10)
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.discard
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully discarded." }
      format.json { head :no_content }
    end
  end

  def my_posts
    @posts = current_user.posts.order(created_at: :desc, status: :asc).page(params[:page]).per(10)
  end

  def publish
    if @post.published!
      redirect_to my_posts_posts_path, notice: "Post Published!"
    else
      redirect_to my_posts_posts_path, status: :unprocessable_entity
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id] || params[:post_id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:body, :media, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  %a.navbar-brand{href: "#"}
    Twitter RipOff
  %button.navbar-toggler{type: "button", 'data-toggle': "collapse", 'data-target': "#navbarSupportedContent", 'aria-controls': "navbarSupportedContent", 'aria-expanded': "false", 'aria-label': "Toggle navigation"}
    %span.navbar-toggler-icon

  - if user_signed_in?
    .collapse.navbar-collapse.mr-auto.w-100.order-md-0#navbarSupportedContent
      %ul.navbar-nav.mr-auto
        %li.nav-item
          %a.nav-link{href: posts_path, class: "#{'active' if current_page?(posts_path)}"}
            All Posts
        %li.nav-item
          %a.nav-link{href: my_posts_posts_path, class: "#{'active' if current_page?(my_posts_posts_path)}"}
            My Posts
      %ul.navbar-nav.mx-auto
        %li.nav-item
          %a.nav-link.mx-auto{:href => new_post_path}
            %i.fa.fa-plus
            New Post
      %ul.navbar-nav.ml-auto
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            %strong= current_user.email
          .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
            %a.dropdown-item{href: edit_user_registration_path} Edit Profile
            .dropdown-divider
            = link_to "Logout", destroy_user_session_path, method: :delete, class: 'dropdown-item'
  - else
    .navbar-collapse.collapse.w-100
      %ul.navbar-nav.ml-auto
        %li.nav-item
          = link_to "Sign up", new_user_registration_path, :class => 'navbar-link'

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %meta{charset: "utf-8"}/
    %meta{content: "IE=edge", "http-equiv": "X-UA-Compatible"}/
    %meta{content: "width=device-width, initial-scale=1, shrink-to-fit=no", name: "viewport"}
    %link{rel: "stylesheet", href:"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css", integrity: "sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm", crossorigin: "anonymous"}
    %link{href: "//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css", rel: "stylesheet"}

    %script{src: "https://code.jquery.com/jquery-3.2.1.slim.min.js", integrity: "sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN", crossorigin: "anonymous"}
    %script{src: "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js", integrity: "sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q", crossorigin: "anonymous"}
    %script{src: "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js", integrity: "sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl", crossorigin: "anonymous"}

    %title= 'Twitter Clone'
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = render 'layouts/navbar'
    .wrapper
      - if notice
        %p.alert.alert-success
          = notice
      - if alert
        %p.alert.alert-danger
          = alert
      = yield

app/views/posts/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |message|
          %li= message
  .row
    .col-sm-12
      .form-group
        = f.label :body
        = f.text_area :body, class: "form-control"
      .form-group
        = f.label :media
        = f.file_field :media, class: "form-control"
  .actions
    = f.submit 'Save'

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
#posts.transitions-enabled
  .row.mr-2
    .col-sm-12
      - @posts.each do |post|
        .post-box.mt-3.mx-auto
          .panel.panel-default
            %span
              .panel-header
                %strong= post.user.email
                %span.ml-5
                  = link_to 'Show', post_path(post)
                .float-right
                  %span.likes-count{id: "post_#{post.id}"}
                    = post.favoritors.count.positive? ? post.favoritors.count : nil
                  %i.fa.fa-thumbs-up.fa-fa-2x.cursor-pointer{class: "#{'liked' if post.favorited_by?(current_user)}", 'data-object-type': post.class.name, 'data-object-id': post.id, id: "thumb_#{post.class.name.downcase}_#{post.id}"}
                %hr/
              .panel-body
                .row
                  .col-md-12
                    %blockquote= post.body
                    - if post.media.attached?
                      = render 'shared/render_media', object: post
                .panel-footer.mt-5
                  - if post.comments.present?
                    %h5
                      Comments
                    - post.comments.order(created_at: :desc).each do |comment|
                      .comment{id: "comment_show_#{comment.id}", 'data-post-id': post.id}
                        = render 'shared/render_comment', object: comment
                      .edit_comment{id: "comment_edit_#{comment.id}", 'data-post-id': post.id}
                        = render 'shared/edit_comment', object: comment
          .new-comment{id: "new_comment_#{post.id}"}
            = render 'shared/comment', object: post

        %hr
  .mt-2
    = page_entries_info @posts, entry_name: 'post'
    .float-right.mr-4
      = paginate @posts

:javascript
  $(document).ready(function(){
    $('.edit_comment').prop('hidden', true)
    $('.comment_edit_button').on('click', function(){
      comment_id = $(this).attr('data-id');
      post_id = $(this).attr('data-post-id');
      console.log(post_id)
      $("#comment_edit_" + comment_id).prop('hidden', false)
      $("#comment_show_" + comment_id).prop('hidden', true)
      $('#new_comment_' + post_id).prop('hidden', true)
    })
  })

app/views/posts/my_posts.html.haml
.entries
  = page_entries_info @posts, entry_name: 'post'
#pins.transitions-enabled.mt-5
  .row.mr-2
    .col-sm-12
      - @posts.each do |post|
        .post-box.mt-3.mx-auto
          .panel.panel-default
            .panel-header
              %smap.status
                Status:
                = post.status.humanize
              %span.float-right.d-flex
                - if post.draft?
                  .mr-2
                    = link_to 'Publish', post_publish_path(post.id)
                = link_to 'Show', post_path(post)
            .panel-body.mt-4
              %blockquote= post.body
              %br/
              - if post.media.attached?
                = render 'shared/render_media', object: post
              .panel-footer.mt-3
                - if post.comments.present?
                  %h5
                    Comments
                  - post.comments.order(created_at: :desc).each do |comment|
                    = render 'shared/render_comment', object: comment
      .mt-2
        = page_entries_info @posts, entry_name: 'post'
        .float-right.mr-4
          = paginate @posts

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
%p#notice= notice
.row.vh-100
  .col-md-8
    %blockquote= @post.body
    - if @post.media.attached?
      = render 'shared/render_media', object: @post
  .col-md-4.comments
    %h5
      Comments
      = "(#{@post.comments.count})"
    .new-comment
      = render 'shared/comment', object: @post
    - if @post.comments.present?
      - @post.comments.order(created_at: :desc).each do |comment|
        = render 'shared/render_comment', object: comment
.options.mt-5
  - if @post.draft? && @post.user == current_user
    = link_to 'Edit', edit_post_path(@post)
  \|
  = link_to 'Back', posts_path
  \|
  - if @post.user == current_user
    = link_to 'Destroy', post_path, method: :delete, data: { confirm: 'Are you sure?' }

app/views/shared/_comment.html.haml
.row
  .col-md-8
    = form_with(model: Comment.new, url: add_comment_comments_path(post_id: object), remote: true, format: :js) do |f|
      = f.text_area :body, placeholder: "Add a comment...", class: "form-control", cols: "30", rows: "1"
      .row.mt-2
        .col-sm-12
          = f.file_field :media, type: 'file', hidden: false, accept: ".jpg, .mp3, .wav, .gif, .mp4, .mpeg"
          %br
          = f.submit 'Comment', class: "btn btn-primary btn-sm float-right mt-n25"

app/views/shared/_edit_comment.html.haml
.row
  .col-md-8
    = form_with(model: Comment.find(object.id), url: update_comment_comments_path(post_id: object), remote: true, format: :js) do |f|
      = f.hidden_field :id, valu: object.id
      = f.text_area :body, placeholder: "Add a comment...", class: "form-control", cols: "30", rows: "1"
      .row.mt-2
        .col-sm-12
          = f.file_field :media, type: 'file', hidden: false, accept: ".jpg, .mp3, .wav, .gif, .mp4, .mpeg", placeholder: 'test'
          - if object.media.attached?
            = link_to object.media.attachment.filename.to_s, rails_blob_path(object.media.attachment)
          %br
          = f.submit 'Comment', class: "btn btn-primary btn-sm float-right mt-n25"

app/views/shared/_render_comment.html.haml
.row.comment.my-3.p-3
  .col-sm-12
    %p
      = object.user.email
    .float-right
      - if object.user == current_user
        %button.btn.btn-secondary.btn-sm.comment_edit_button{'data-id': object.id, 'data-post-id': object.parent_id}
          Edit
      %span.likes-count{id: "comment_#{object.id}"}
        = object.favoritors.count.positive? ? object.favoritors.count : nil
      %i.fa.fa-thumbs-up.fa-fa-2x.cursor-pointer{class: "#{'liked' if object.favorited_by?(current_user)}", 'data-object-type': object.class.name, 'data-object-id': object.id, id: "thumb_#{object.class.name.downcase}_#{object.id}"}
    %p
      = object.body
    - if object.media.attached?
      = render 'shared/render_media', object: object

app/views/shared/_render_media.html.haml
.row
  .col-sm-12
    - content_type = object.media.attachment.content_type
    .media
      - if content_type["audio"]
        %audio{:controls => "true", :preload => "true"}
          %source{:src => rails_blob_path(object.media.attachment), type: content_type}
      - elsif content_type["video"]
        .video
          %video{:controls => "true", :preload => "true"}
            %source{:src => rails_blob_path(object.media.attachment), type: content_type}
      - elsif content_type["image"]
        .image
          %img{:src => rails_blob_path(object.media.attachment)}
      - else
        = link_to object.media.attachment.filename.to_s, rails_blob_path(object.media.attachment)